### ISSUE TITLE
Convergence proof

### ISSUE THREAD

**Issue by capilano** [irugina/meta-image-translation#1]
Were you able to establish that the GAN's converge? The original paper only describes convergence at an exact equilibrium and show that the only solution is Pg = Pdata. None of the inner loop learners meet this condition (the meta leaner provides feedbacks and so this violates the zero -sum game). How did you verify that there was no mode collapse and memorization, did all the paths (i.e were all adaptation subtasks analyzed to be non-mutually exclusive) I have seen good recon loss and low GAN losses but poor generalization.
Would be happy to take the discussion forward if interested. I stumbled on this while doing Chelsea Fynn's course at Stanford, during my final project. Thanks

**Comment by irugina** [comment]
Hello,
Thank you for your question and interest in our work. You're right that theoretical guarantees for adversarial training do not extrapolate to our setup, and we did not attempt generalizing them either. We explicitly acknowledge mode collapse does happen in section 3.4.2 and discuss the trade-offs we've encountered throughout our experimental sections.

**Comment by capilano** [comment]
Thank you for your reply. I was unable to stabilize even toy GAN's using this approach.  For regular generation tasks, I was unable to come up with a way to guarantee that memorization won't occur. For image translation tasks too, we ran into these issues as well as convergence issues. Did you face these issues as well in your training? I am working on some hard results about the convergence guarantees, will let you know when I am done with the work. Thanks for your reply, again!

**Comment by rdangovs** [comment]
We didn't face many issues with memorization / instabilities, but we agree that training GANs is tricky and performance varies. Happy to chat further if you'd like.
