### ISSUE TITLE
Pre-trained model based on SimCLR

### ISSUE THREAD

**Issue by yss0306** [irugina/meta-image-translation#2]
Hello! I'm a master student of meteorology and I'm very interested in your work. I have read your master thesis about transforming satellite images to radar images. The chapter 5 is about using self-supervised pretraining to enhance the UNet network but I cannot find this part in your code. Could you provide the main ideas of it?

**Comment by irugina** [comment]
Hello, and thank you for your interest in our work! You're right, this repository only has code for loading pretrained models, and not the code for pretraining: sorry about that. If i remember correctly, we used the encoder model definitions from this repo, torchvision for data augmentation, and another simclr package for the actual pretraining.

**Comment by yss0306** [comment]
Thank you for your nice reply! I'm  working on using pretrained model to handle precipitation nowcasting. Your work has greatly inspired me. But the repo of the encoder model definitions doesn't seem to open. Could you provide the detailed link? What's more, I am an outsider in deep learning and I have a simple question. Why the parameters of encoder of SimCLR can be loaded to the U-Net model? Are they share same architecture? Thanks a lot!

**Comment by rdangovs** [comment]
Hello, 

Thanks for your interest in our work. It is great that our work is useful to your research. I will upload some SimCLR pre-training code soon. 

The U-Net model can be decomposed into an encoder and a decoder. SimCLR only pre-trains the encoder. The decoder is initialized randomly for fine-tuning. I can share some code snippets/ upload the code soon. 

Happy to answer more questions/ stay in touch during your research. 

Best wishes, 
Rumen

**Comment by yss0306** [comment]
Thank you for your reply! I'm very looking forward to the next code and that will be exciting. I think your work is very farsighted. DL for weather forecasting requires powerful pre-trained models and training methods for real-world few-shot data in the future.

I undersand the encoder of SimCLR as a part of U-Net because of your explaination. Looking forward to further communication with you regarding to the pre-trained models.

**Comment by rdangovs** [comment]
Hello! 

Thank you for your patience. I have posted the pre-training code here: https://github.com/irugina/meta-image-translation/blob/main/train_cl.py

Please let me know if you have questions :)

Best wishes

**Comment by yss0306** [comment]
Thank you for your nice supplement!

The code is well-organized and it helps me a lot. I now undertand the details of contrastive learning. I believe it can contribute a lot to my future research. 

Thank you again and best wishes.
